<?php

/**
 * DO NOT EDIT THIS FILE as it will be overwritten by Pbj Compiler process.
 *
 * Registers all of the pbj schemas with the MessageResolver.
 *
 * This file has been auto-generated by the Pbj Compilter on 2016-03-03 14:22:24 PST.
 */

\Gdbots\Pbj\MessageResolver::registerMap([
    'acme:blog:command:update-article' => 'Acme\Schemas\Blog\Command\UpdateArticleV2',
    'acme:blog:command:update-article:v1' => 'Acme\Schemas\Blog\Command\UpdateArticleV1',
    'acme:blog:command:update-article:v2' => 'Acme\Schemas\Blog\Command\UpdateArticleV2',
    'acme:blog:entity:article' => 'Acme\Schemas\Blog\Entity\ArticleV1',
    'acme:blog:entity:comment' => 'Acme\Schemas\Blog\Entity\CommentV1',
]);
