<?php
/**
 * DO NOT EDIT THIS FILE as it will be overwritten by Composer as part of
 * the installation/update process.
 *
 * Registers all directories from all required packages which are of
 * of the type "pbj-schema-store".
 */
$vendorDir = realpath(__DIR__.'/vendor');

\Gdbots\Pbjc\SchemaStore::addDirs([
    $vendorDir.'/gdbots/schemas/schemas/',
]);
